{
    'name': "hr_hospital",
    'version': '1.2',
    'summary': "Hospital Management Module",
    'author': "Max Tyshchuk",
    'category': 'Productivity/Hospital',
    'depends': [
        'base',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/disease_data.xml',
        'views/doctor_speciality_view.xml',
        'views/contact_person_view.xml',
        'views/doctor_view.xml',
        'views/patient_view.xml',
        'views/disease_view.xml',
        'views/patient_visit_view.xml',
        'views/medical_diagnosis_view.xml',
        'views/patient_doctor_history_view.xml',
        'views/doctor_schedule_view.xml',
        'wizard/mass_reassign_doctor_view.xml',
        'wizard/disease_report_wizard_view.xml',
        'wizard/reschedule_visit_wizard_view.xml',
        'wizard/doctor_schedule_wizard_view.xml',
        'wizard/patient_card_export_wizard_view.xml',
        'views/menu.xml',

    ],
    'demo': [
        'demo/speciality_demo.xml',
        'demo/doctor_demo.xml',
        'demo/patient_demo.xml',
        'demo/visit_demo.xml',
        'demo/diagnosis_demo.xml',
        'demo/schedule_demo.xml',
        'demo/history_demo.xml',
    ],
    'application': True,
    'license': 'LGPL-3',
}
